### ISSUE TITLE
È possibile visualizzare il PUN orario?

### ISSUE THREAD

**Issue by pullaf** [virtualdj/pun_sensor#14]
Intanto complimenti per l'integrazione, e grazie

Dato che ultimamente le tariffe della F2 sono diventate più alte di quelle F1 e F3, con un picco soprattutto intorno alle 20-22 (maledetti), sarebbe possibile modificare lo script per esporre tutte le tariffe ora per ora, così da farne un grafico e potersi regolare su quando è meglio consumare? Ad esempio, se so che alle 20 è più alto che alle 21 faccio partire prima la lavatrice e viceversa se alle 22 è già più basso posso aspettare

Vedo che comunque estrai dall'XML tutti gli orari con relativi PUN e li salvi, poi però mi pare di capire che usi questo array per fare la media delle fasce e quindi il dettaglio non è esposto, corretto?

**Comment by virtualdj** [comment]
> sarebbe possibile modificare lo script per esporre tutte le tariffe ora per ora, così da farne un grafico

Chiaramente sarebbe possibile, ma non sarebbero poi troppi i sensori considerando 1 sensore per ogni ora?

> usi questo array per fare la media delle fasce e quindi il dettaglio non è esposto, corretto?

Corretto. Il sensore espone il prezzo medio che si va a comporre giorno dopo giorno nel mese, dato che alla fine tu paghi il valore medio mensile, non il giornaliero. Quindi nell'ipotesi precedente, bisognerebbe fare una media dei prezzi di ogni ora, mensilmente... tuttavia c'è il problema dei festivi, che andrebbero ad abbassare la media oraria. Non mi convince!
