### ISSUE TITLE
Richiesta di completamento dell'integrazione con Home Assistant e disponibilità su HACS

### ISSUE THREAD

**Issue by mauro-midolo** [virtualdj/pun_sensor#17]
Ciao @virtualdj ,

Sono un appassionato utente di Home Assistant e ho scoperto l'integrazione che hai creato per monitorare i valori del costo PUN della corrente elettrica. È un'integrazione molto utile per il mio sistema di automazione domestica, e apprezzo molto il tuo lavoro su questo progetto.

Tuttavia, ho notato che l'integrazione non è ancora completamente integrata con HACS (Home Assistant Community Store), il che rende più complicato per gli utenti come me trovarla e installarla. Vorrei gentilmente chiedere se potessi considerare l'opportunità di completare l'integrazione con HACS in modo che possa essere facilmente accessibile e installabile tramite il sistema di gestione delle integrazioni di Home Assistant.

So che questo richiede tempo e sforzi aggiuntivi, ma credo che renderà l'uso di questa integrazione molto più conveniente per la comunità di Home Assistant e contribuirà a rendere il tuo lavoro ancora più apprezzato. 
Se hai bisogno di assistenza o ulteriori dettagli, sarò lieto di fornire supporto e rispondere a eventuali domande.

Grazie per il tuo contributo a Home Assistant e per la tua considerazione.

**Comment by virtualdj** [comment]
Ciao, ho dato un'occhiata alla procedura nella documentazione di HACS ma oltre alle varie validazioni con le Actions di GitHub sembra sia obbligatoria anche l'immagine (branding). Inoltre questa è una integrazione dedicata solo al pubblico italiano... 

Domanda: è davvero necessario? Perché alla fine la differenza è **un clic in più in HACS** per aggiungere l'URL della repository custom, come indicato nel README di questa integrazione.

Dopotutto molte altre integrazioni che uso sfruttano lo stesso metodo, anche se sono popolari. Non sono cioè inserire nel repo di HACS direttamente.

Essendo una funzionalità di nicchia, mi sento un po' più a mio agio così...

**Comment by virtualdj** [comment]
Ciao, ecco la procedura per installare l'integrazione con HACS e il repository personalizzato (magari successivamente lo aggiungerò al README).

1. Aggiungere il repository in HACS

![Passo_1](https://github.com/virtualdj/pun_sensor/assets/3251704/2ac92e03-1b3d-408b-a492-452e33f8c83f)

2. Digitare il nome dell'URL

![Passo_2](https://github.com/virtualdj/pun_sensor/assets/3251704/f80f94f1-4833-4f6b-9ad3-3be3ba7c8dbd)

3. Chiudere la finestra popup

![Passo_3](https://github.com/virtualdj/pun_sensor/assets/3251704/13e38b28-2234-4c39-8ba0-7128cccb8abc)

4. Cercare la nuova integrazione

![Passo_4](https://github.com/virtualdj/pun_sensor/assets/3251704/8b09c873-e32c-4cfa-ae34-d542b99ee5a8)

5. Fare clic su **Scarica**

![Passo_5](https://github.com/virtualdj/pun_sensor/assets/3251704/9b83a213-e1cf-4675-a301-f0a469d7b65c)

6. Confermare l'installazione, riavviare Home Assistant e aggiungere l'integrazione normalmente

![Passo_6](https://github.com/virtualdj/pun_sensor/assets/3251704/9616eaba-6148-4b90-8df3-0abce59b06f6)

**Comment by mauro-midolo** [comment]
Grazie mille per la guida, te lo consigliavo solo per aiutare la community a trovare la tua integrazione che è molto utile in questo momento storico.
Anche io gestisco un'integrazione e l'ho integrata con hacs senza troppo sforzo.

In ogni caso sei tu a decidere cosa fare.
Grazie mille!

**Comment by virtualdj** [comment]
Il suggerimento è ben accetto e ti ringrazio perché mi ha dato il modo di approfondire...

Solo ritengo che non sia una funzionalità "degna" di essere pubblicata globalmente, ecco (a causa dei limiti geografici).

**Comment by mauro-midolo** [comment]
Ho creato una pull request con alcune migliorie per l'integrazione di HACS.
Anche se non è pubblicata sul repo di Hacs, dopo la merge della pr avrà tutti gli standard di conformità.

**Comment by lucasaba** [comment]
Grazie del thread! Sono finalmente riuscito a configurare il componente!

E grazie mille del componente!
