### ISSUE TITLE
Miglioria/Fork: prezzi zonali orari (PO) per RID

### ISSUE THREAD

**Issue by g1za** [virtualdj/pun_sensor#18]
Un'idea che potrebbe essere interessante da implementare basandosi sull'integrazione corrente (magari cambiando solo la sorgente dei dati e permettendo di selezionare la zona di interesse): sarebbe possibile scaricare anche i prezzi medi zonali orari? Questi vengono utilizati per pagare l'energia immessa in rete da un impianto fotovoltaico tramite il ritiro dedicato.

Riferimenti:
* [https://www.gse.it/servizi-per-te/fotovoltaico/ritiro-dedicato/regolazione-economica-del-servizio](url)
* [https://www.mercatoelettrico.org/it/mercati/mercatoelettrico/Zone.aspx](url)

Se ricordo bene tu utilizzi il file XLS dalla sezione dati storici; per fare questa cosa bisognerebbe permettere all'utente di scegliere la colonna da cui recuperare i dati, per l'italia scegliendo tra (tutte presenti nel file):
- CALA | Calabria
- CNOR | Centro Nord
- CSUD | Centro Sud
- NORD | Nord
- SARD | Sardegna
- SICI | Sicilia
- SUD | Sud

Che ne pensi?
Grazie e ciao!

**Comment by virtualdj** [comment]
> Se ricordo bene tu utilizzi il file XLS dalla sezione dati storici

Non i file Excel, ma i dati grezzi XML.

> per fare questa cosa bisognerebbe permettere all'utente di scegliere la colonna da cui recuperare i dati, per l'italia scegliendo tra (tutte presenti nel file)

Non penso affatto sia impossibile, solo che non conoscendo la materia non mi sento propriamente "ferrato". Credo possa essere qualcosa di più adatto ad un fork, da parte di chi ne capisce di più... 😃

**Comment by g1za** [comment]
Chiaro :)
