### ISSUE TITLE
Estensione del progetto

### ISSUE THREAD

**Issue by virtualj** [virtualdj/pun_sensor#2]
Volevo suggerire se possibile parsare dal file xml oltre al PUN anche altri dati, in particolare i prezzi zonali tipo CSUD, CNORD etc che servono per la valorizzazione delle immissioni in rete del fotovoltaico.
Similmente sarebbe comodo avere anche i dati trimestrali aggiornati da ARERA su https://www.arera.it/allegati/dati_documenti/prezzi/elettricita-domestici.xls. Questo permetterebbe di poter calcolare in maniera completa il costo in bolletta.
Per il momento ti ringrazio tantissimo dell'attuale lavoro sul pun!

**Comment by virtualdj** [comment]
> in particolare i prezzi zonali tipo CSUD, CNORD etc che servono per la valorizzazione delle immissioni in rete del fotovoltaico

Purtroppo questo non è il mio "campo" quindi diciamo che non saprei come trattarli quei dati; in ogni caso puoi prendere ispirazione dal codice, per estrarre le altre colonne basta recuperare il nome del campo XML e fare come in questa linea:

https://github.com/virtualdj/pun_sensor/blob/e023d418bb2fd782de307f3718e51aa544b536e2/custom_components/pun_sensor/__init__.py#L228


> Similmente sarebbe comodo avere anche i dati trimestrali aggiornati da ARERA su https://www.arera.it/allegati/dati_documenti/prezzi/elettricita-domestici.xls

Per calcolare i prezzi del maggior tutela? In quel caso un sensore che si aggiorna una volta al giorno non avrebbe molto senso; semmai bisognerebbe partire da un qualcosa che facesse il parsing dell'Excel come avevo fatto nel progetto alternativo **pun-fasce**:

https://github.com/virtualdj/pun-fasce/blob/45ea212dd4c53f59f648e548eaf445668ab98b94/pun-fasce.py#L66-L103

Però non mi sento di integrarlo qui essendo una cosa diversa (seppure legata).

> Questo permetterebbe di poter calcolare in maniera completa il costo in bolletta.

Infatti il motivo per cui mi sono creato questo sensore è per stimare quanto potrò pagare a fine mese, visto che comunque il prezzo viene calcolato sulla media di tutte le fasce orarie. Aggiungere tasse e quant'altro si può fare con un template sensor in Home Assistant.

Piuttosto mi piacerebbe capire come calcolare correttamente il prezzo per la fascia F23, cosa che non sono riuscito a fare in nessun modo (o perlomeno i miei calcoli non rispecchiano quelli delle tabelle che si trovano in giro).
