### ISSUE TITLE
Sensor template prezzo al dettaglio

### ISSUE THREAD

**Issue by ninoger** [virtualdj/pun_sensor#20]
Ciao, uso da qualche mese il tuo component. Tutto ok. Ma per quanto riguarda il sensore del prezzo non capisco quali dati prendere dalla bolletta. Ho NeN. Puoi dare qualche indicazione? Grazie molte.

**Comment by virtualdj** [comment]
Ciao, guarda, in realtà bene non lo so neppure io!
Di certo tutti i prezzi sono basati sul PUN, cioè quello che indica il sensore di Home Assistant, al quale si aggiunge uno _spread_, cioè un incremento, definito in base al tuo contratto. Poi devi guardare nel dettaglio della bolletta quali sono i costi per kWh "fissi", come il dispacciamento e le perdite di rete (li riconosci perché le unità di misura sono €/kWh) che quindi dovrai sommare e poi aggiungi l'IVA.

È tutto un calcolo approssimativo, ovviamente, ma aiuta a dare l'idea di quanto si spenderà perché comunque il PUN è proporzionale al costo per kWh.

Il vero motivo per cui ho creato questa integrazione è avere un'idea di quando è più conveniente consumare l'energia elettrica, perché calcolare a priori il costo della bolletta in base ai consumi non è certo semplice!

**Comment by ninoger** [comment]
Ciao, grazie per la risposta.
Si, ho capito che si tratta di una approssimazione, ma non ho capito come mettere i miei dati. Cioè, nel tuo esempio di sensor template c'è:

 {{ (1.1 * (states('sensor.pun_prezzo_fascia_corrente')|float(0) + 0.0087 + 0.04 + 0.0227))|round(3) }}

1.1 cosa è? E gli altri numeri? Nella mia bolletta ce ne sono un'infinità di €/kWh. Se riesci a darmi ancora qualche input te ne sono grato. Comunque il tuo lavoro è molto utile. Ti segnalo che credo di aver trovato un refuso proprio nell'esempio: il sensore è chiamato sensor.pun_prezzo_fascia_corrente, mentre l'integrazione crea sensor.pun_fascia_corrente.
Grazie.

**Comment by virtualdj** [comment]
> 1.1 cosa è?

Il 10% di IVA che viene aggiunto al totale.

> E gli altri numeri? Nella mia bolletta ce ne sono un'infinità di €/kWh.

Sono loro, praticamente al prezzo attuale in €/kWh (definito da `states('sensor.pun_prezzo_fascia_corrente')|float(0)`) vengono aggiunti lo spread del gestore e i costi fissi per kWh (es. dispacciamento, perdite di rete, ecc.); quei numerini lì nell'esempio non mi ricordo dove li avevo trovati, ma sono appunto "fissi" per ogni kWh e quindi vanno aggiunti alla tariffa della fascia corrente.

Puoi comunque crearti tu la formula come preferisci, in modo da ottenere un risultato congruo (o comunque proporzionale) a quello che hai in bolletta. Il problema è che la bolletta la vedrai solo successivamente, quindi dovresti segnarti i valori delle 3 fasce (`sensor.pun_fascia_f1`, `sensor.pun_fascia_f2` e `sensor.pun_fascia_f3`) a fine mese e poi confrontare con la bolletta quanto hai pagato ogni kWh in ciascuna delle fasce... con quello trovi il moltiplicatore corretto.

> Ti segnalo che credo di aver trovato un refuso proprio nell'esempio: il sensore è chiamato sensor.pun_prezzo_fascia_corrente, mentre l'integrazione crea sensor.pun_fascia_corrente.

Mi pare sia corretto `sensor.pun_prezzo_fascia_corrente`, perché l'altro `sensor.pun_fascia_corrente` che citi è l'indicazione della fascia attuale. Lo vedi bene se vai nella sezione **Strumenti per sviluppatore > Stati** di Home Assistant

![Screenshot pun_prezzo_fascia_corrente vs pun_fascia_corrente](https://github.com/virtualdj/pun_sensor/assets/3251704/7cc616ae-81ab-4463-9d4b-22a823b8d9ea)

**Comment by ninoger** [comment]
Ciao. Per il sensore ok, non avevo capito il tutto. Ho modificato il sensore con i miei dati (se sono riuscito ad interpretarli correttamente) e sembra restituire un risultato congruo. Vedremo il prossimo mese come varierà.

Ti segnalo un'altra cosa: stamattina la fascia corrente è rimasta F3. Per aggiornarla a F1 ho dovuto ricaricare l'integrazione. Non ricordo anomalie in precedenza: Forse qualcosa con gli ultimi aggiornamenti?

Grazie davvero per le indicazioni e buon lavoro.

**Comment by virtualdj** [comment]
C'è un'altra issue aperta per il cambio fascia che non funziona, la #16, che però io non riesco a replicare (né in passato né ora).
Sarebbe utile avere i log, come scritto nel mio ultimo post lì, se succede di nuovo...

**Comment by ninoger** [comment]
> C'è un'altra issue aperta per il cambio fascia che non funziona, la #16, che però io non riesco a replicare (né in passato né ora).
> Sarebbe utile avere i log, come scritto nel mio ultimo post lì, se succede di nuovo...

Si, avevo letto tempo fa e non mi sono ricordato stavolta. Se ricapita provo a prendere il log. Grazie
