### ISSUE TITLE
Mancanza Icona

### ISSUE THREAD

**Issue by sagitt** [virtualdj/pun_sensor#22]
Ciao, penso tu te ne sia accorto ma manca l'icona del servizio.
Sarebbe bello averla.

grazie

<img width="319" alt="Screenshot 2023-11-05 alle 16 17 23" src="https://github.com/virtualdj/pun_sensor/assets/169086/e1857cc0-998e-416c-b15e-4ab999802115">

**Comment by virtualdj** [comment]
Con icona intendi il _branding_?
Sì in realtà non l'ho messa apposta, perché non essendo un'integrazione legata ad un marchio specifico non credo sia opportuna (esistono linee guida in merito?). Insomma, non mi convinceva un'icona generica, che non rappresenta poi l'integrazione stessa.

In più non credo che i numeri di installazione bassi di un'integrazione tipicamente italiana giustifichino il branding...

**Comment by EnricoBettella** [comment]
Il logo per le integrazioni custom non è obbligatorio, però rende di sicuro l'integrazione più bella e riconoscibile nella UI. [Qui](https://developers.home-assistant.io/blog/2020/05/08/logos-custom-integrations/) spiegano che è presente una [repository Brands](https://github.com/home-assistant/brands) per tutti i loghi e icone delle integrazioni, e anche quelle custom vanno caricate lì per apparire.
