### ISSUE TITLE
Possibile richiesta feature

### ISSUE THREAD

**Issue by Claudio1L** [virtualdj/pun_sensor#23]
Ciao, intanto grazie per il lavoro che hai fatto, l'ho scoperto tre giorni fa per caso e mi aiuta ad introdurre la granularità necessaria per le tre fasce. Prima usavo multiscrape ma riuscivo a fare solo un medione giornaliero. Oltre ad avere molti errori quando non riusciva a scaricare i valori.

Ti volevo chiedere questo: Ho notato in bolletta che ci sono delle voci aggiuntive che sono proporzionali alla quantità di kWh di potenza attiva. Ad esempio le perdite o le spese di trasporto. Se fosse possibile introdurre una feature in cui definire un x % aggiuntivo, rispetto al prezzo raccolto, ad esempio aggiungendo dei sensori con "PUN lordo" , con un po' di tuning si potrebbe avvicinarsi molto ai costi reali in bolletta. Ovviamente è possibile farlo a posteriori con dei template sensor, ma credo che avendo l'opzione alla "fonte" sarebbe più flessibile, immediato e pulito.

**Comment by virtualdj** [comment]
> Se fosse possibile introdurre una feature in cui definire un x % aggiuntivo

Questo però puoi già farlo con un _template sensor_, come indicato nell'esempio sul README (la pagina principale del progetto).

**Comment by virtualdj** [comment]
> Ovviamente è possibile farlo a posteriori con dei template sensor, ma credo che avendo l'opzione alla "fonte" sarebbe più flessibile, immediato e pulito

Lo so, però ogni sensore che aggiungo "pesa" per Home Assistant (anche come log e storico che deve conservare). Ad esempio io uso InfluxDB per le statistiche a lungo termine e lì si vede subito, con le dimensioni del database, quando inizi a memorizzare dati aggiuntivi.

Quindi se il valore è direttamente calcolabile dai sensori già forniti, sono contrario ad aggiungerne altri... la risposta giusta è "template sensor".
