### ISSUE TITLE
Fascia bioraria

### ISSUE THREAD

**Issue by xalex75** [virtualdj/pun_sensor#24]
Ciao.
Ho appena scoperto ed integrato il tuo lavoro nella mia istanza di HA.
Nel mio caso ho una tariffa bioraria, quindi ho F1 (dalle 8 alle 19) e F23 (dalle 19 alle 8 e tutto sabato, domenica e festivi), mentre i tuoi sensori danno valori distinti per F2 e F3.
Volevo quindi sapere se fosse possibile introdurre il sensore per la F23.
Grazie.

**Comment by virtualdj** [comment]
> Volevo quindi sapere se fosse possibile introdurre il sensore per la F23.

Guarda, era una delle cose che volevo fare fin dall'inizio, ma non sono stato in grado di capire come calcolarla esattamente. Se riesci a trovarmi la documentazione e verifichiamo che i calcoli corrispondano a quelli pubblicati (ad esempio A2A), la aggiungo sicuramente.

Ma finora ho sempre fallito: il numero mensile non corrisponde ai [dati pubblicati](https://www.a2a.it/assistenza/tutela-cliente/indici/indice-pun) (a differenza della F1, F2, F3 e giornaliera).

**Comment by xalex75** [comment]
Ah cavolo.... credevo e speravo che ci fosse una fonte definita dalla quale attingere, non che andasse calcolata.
Prima usavo lo scraper che attingeva da a2a e prendeva direttamente il valore F23.
Non ho idea di se e come possa essere calcolata, pensavo proprio che fosse direttamente esposta.

Lo scraper era così configurato:

` - platform: scrape
    name: PUN F23
    resource: https://www.a2aenergia.eu/assistenza/tutela-cliente/indici/indice-pun
    select: "td"
    index: 5
    unit_of_measurement: €`

**Comment by virtualdj** [comment]
Eh ma è una cosa "diversa"... Se tu peschi il valore dal sito A2A con multiscrape vedi il prezzo del PUN del mese appena trascorso (più il tempo che ci mettono a pubblicare i dati).

Questa integrazione, invece, scarica i dati giorno per giorno e calcola le medie dei prezzi per fasce orarie; queste saranno via via più precise fino a fine mese, quando le medie corrisponderanno esattamente ai valori che A2A e gli altri pubblicheranno.
Ad esempio, il PUN di F1 è la media dei prezzi nella fascia oraria F1; la F23 dovrebbe essere la media nelle fasce F2 e F3 ma facendo i calcoli questi non corrispondono... E non mi va di pubblicare qualcosa se il valore è diverso da quello ufficiale... solo vorrei capire come fanno a calcolarlo!

**Comment by xalex75** [comment]
Capisco... peccato.
Mi piaceva la tua integrazione proprio perchè del prezzo del mese appena trascorso me ne faccio relativamente poco.
Peccato che non sia possibile avere da loro le info necessarie per il calcolo.
Amen...

**Comment by virtualdj** [comment]
Ma infatti il motivo per cui ho creato questa integrazione è proprio questo, volevo avere un costo indicativo che però seguisse il PUN (poi è chiaro che in bolletta si paga di più) in modo da capire quando attivare determinati dispositivi energivori, come la ricarica di un auto elettrica ad esempio.

Non riesco a spiegarmi perché l'unico calcolo che non "torna" sia proprio la F23. Anche perché se le fasce le rilevo correttamente (lo stato F1 / F2 / F3 in questa integrazione) l'algoritmo che calcola la media è lo stesso...

**Comment by virtualdj** [comment]
Se vuoi / volete dilettarvi, ti allego un documento Excel con il mese di **ottobre 2023**, che non ha festività speciali.
Nel file Excel si calcolano le fasce per ciascun prezzo, scaricato dall'archivio 2023 da [qui](https://www.mercatoelettrico.org/It/MenuBiblioteca/Documenti/Anno2023.zip) e filtrato solo per il mese di ottobre.

[ALLEGATO: Esempio_Ottobre_2023.xlsx](https://github.com/virtualdj/pun_sensor/files/13322687/Esempio_Ottobre_2023.xlsx)

Sulla destra il confronto tra il valore calcolato (arrotondato alla 5ª cifra sebbene ne siano mostrate 6) e [quello di A2A](https://www.a2a.it/assistenza/tutela-cliente/indici/indice-pun):

![Risultati calcolo ottobre 2023](https://github.com/virtualdj/pun_sensor/assets/3251704/ad42d2fe-0b35-48b2-919c-f5a735a4eb4a)

A parte un "glitch" sulla F3, che però c'è solo per ottobre (e non negli altri mesi) quindi potrebbe essere benissimo un errore di trascrizione di A2A, si nota come **la F23 sia ben differente**!

Se qualcuno conosce un metodo per fare risultare quel numero combinando le fasce orarie, me lo faccia sapere... io ci ho provato ma non sono riuscito a trovarlo!

**Comment by virtualdj** [comment]
## Calcoli e confronto con tabelle A2A

Qui di seguito i valori calcolati usando Python e i dati per tutto il 2023, usando l'algoritmo del file Excel.
```text
Mese         MO (€/kWh)    F1 (€/kWh)    F2 (€/kWh)    F3 (€/kWh)    F23 (€/kWh)
10/2023      0.134280      0.144560      0.148630      0.119090      0.129330
09/2023      0.115700      0.118550      0.128080      0.105990      0.114350
08/2023      0.111890      0.110260      0.128120      0.104480      0.112670
07/2023      0.112090      0.114910      0.122320      0.104340      0.110820
06/2023      0.105340      0.108200      0.117960      0.096610      0.103990
05/2023      0.105730      0.109990      0.119810      0.095110      0.103680
04/2023      0.134970      0.135550      0.152050      0.126400      0.134750
03/2023      0.136380      0.139780      0.151950      0.124660      0.134630
02/2023      0.161070      0.174330      0.172890      0.144220      0.154620
01/2023      0.174490      0.196240      0.184240      0.155100      0.164700
```
Questi invece i valori pubblicati da A2A, con evidenziati in **rosso** quelli diversi.

![Dati dal sito A2A](https://github.com/virtualdj/pun_sensor/assets/3251704/9770c47e-eb54-408f-8643-bdb40d16f640)

Se avete idee, sono le benvenute.

## Documentazione online sul calcolo fascia F23

Di certo **non è vero** quello che scrivono molti siti in merito alla F23, queste le mie ricerche.

### [A2A](https://www.a2a.it/assistenza/tutela-cliente/indici/indice-pun)
![A2A](https://github.com/virtualdj/pun_sensor/assets/3251704/64666b9b-eaf9-462b-afca-bdbfb18722ff)
### [Switcho](https://www.switcho.it/blog/luce-gas/pun-energia/)
![Switcho](https://github.com/virtualdj/pun_sensor/assets/3251704/4f191387-99b6-4739-aa9f-736aaa56371d)
### [Arera](https://bolletta.arera.it/bolletta20/index.php/glossario/fasce-orarie)
![Arera](https://github.com/virtualdj/pun_sensor/assets/3251704/e6ee6f16-3fce-46ed-b47f-4252d29fa451)
### [Bolletta-energia.it](https://bolletta-energia.it/luce/fasce-orarie)
![Bolletta-energia.it](https://github.com/virtualdj/pun_sensor/assets/3251704/0248ae98-3666-4a9c-bacf-48e2ed9d0f0d)
### [Abbassalebollette.it](https://www.abbassalebollette.it/glossario/pun-prezzo-unico-nazionale/#Come_si_calcola_il_PUN_e_i_valori_di_PUN_di_picco_e_fuori_picco)
![Abbassalebollette.it](https://github.com/virtualdj/pun_sensor/assets/3251704/77355a6a-6e91-4b3d-a085-5f94407c2980)

**Comment by xalex75** [comment]
Direi che di impegno ce ne hai messo!
Speriamo che qualcuno possa illuminarci sul calcolo della F23, in ogni caso complimenti per il lavoro!

**Comment by virtualj** [comment]
Ragazzi non chiedetemi come ci sono riuscito e perchè sia così... Ma il risultato di F23 sembra essere legato dalla formula F2*46%+F3*54%. Se guardate nel mio file mi ritornano corretti i valori di tutti i mesi del 2023 tranne gennaio, ma giusto per qualche millesimo di differenza.
Mi sembra una bella fregatura perchè nella realtà le ore in F2 sono circa il 35% e quelle F3 il 65% a livello annuo:
https://docs.google.com/spreadsheets/d/1HEMXjlpRSkaYV91uomF_FbJHd_D0oigDvIDBTrGY8i8/edit#gid=950040340
Sarebbe curioso capire da dove viene questa ripartizione

**Comment by xalex75** [comment]
Io non ti chiedo nulla, ma se ci sei riuscito ti ringrazio a manetta!!! :-D

**Comment by virtualdj** [comment]
> Ragazzi non chiedetemi come ci sono riuscito e perchè sia così... Ma il risultato di F23 sembra essere legato dalla formula F2*46%+F3*54%

@virtualj Cacchio avevo letto una cosa del genere ma **mi sembrava troppo assurdo**, perché era l'unica fonte che scriveva questo... Eccola:

### [CH4 Italia](https://www.ch4-italia.it/offerta-gas-e-luce/offerta-luce-e-gas-pubblica-amministrazione/)

![CH4 Italia](https://github.com/virtualdj/pun_sensor/assets/3251704/709451d7-c692-4810-809c-e6e4e31cb4cd)

Qui parlano però di F2 * 45% e F3 * 55% ma mi sembra strano siano tutti d'accordo su queste percentuali "inventate".

Anche perché poi la frase continua col mono-orario anch'esso con pesi diversi tra le fasce e io nell'integrazione non li calcolo così, eppure il risultato viene corretto. Quindi chi ha ragione?

> Mi sembra una bella fregatura perchè nella realtà le ore in F2 sono circa il 35% e quelle F3 il 65% a livello annuo

Infatti e soprattutto a parte questi di CH4 nessun altro cita quelle percentuali (o io non sono in grado di trovare documentazione). Aiuto!

**Comment by virtualj** [comment]
Su alcuni siti ho trovato questa dicitura, ma sul GME non trovo riscontro di dove siano pubblicati questi valori
![immagine](https://github.com/virtualdj/pun_sensor/assets/4136881/0ee64ecc-fb7d-4d4c-80b8-646391e55192)

**Comment by virtualdj** [comment]
Sinceramente la frase relativa all'F23 mi pare stia dicendo quello che già calcolavamo: ponderata tra F2 e F3 in base all'orario... ma il calcolo non torna e sembra come hai detto tu una percentuale fissa.

**Comment by virtualj** [comment]
Sì, ma c'è scritto in base agli orari pubblicati dal GME e non è detto che siano le ore reali di quel mese. Inoltre non si spiega perchè questo valore sia uguale per tutti i mesi, quando in realtà il rapporto tra le ore F2 ed F3 è sicuramente variabile in base ai weekend/festività presenti nel mese. L'unico valore ocmunque che mi sembra sia pubblicato mensilmente dal GME e che contiene le ore è il seguente:
https://mercatoelettrico.org/It/MenuBiblioteca/Documenti/20231103PrezzomedioperfasceOttobre2023.pdf
![immagine](https://github.com/virtualdj/pun_sensor/assets/4136881/74a5f514-19c6-4436-a828-a66100fd2d06)
Ma purtroppo facendo il rapporto con queste ore viene il mio 34%/66% e non 46/54

**Comment by virtualdj** [comment]
Quindi che facciamo?

**Comment by xalex75** [comment]
Guarda... per me, se i conti in qualche modo ti tornano, mi farebbe comodo avere la tariffa nell'integrazione, altrimenti non posso usarla. Poi se anche sballassa qualcosina, è mille volte meglio di nulla. Magare potresti mettere un disclaimer avvisando che la F23 è ancora in fase di studio...

**Comment by virtualj** [comment]
Puoi crearti il template in autonomia così
![immagine](https://github.com/virtualdj/pun_sensor/assets/4136881/1cc47cbd-44bf-45e0-ba41-bf12baf482d3)

**Comment by xalex75** [comment]
> Puoi crearti il template in autonomia così ![immagine](https://private-user-images.githubusercontent.com/4136881/287340570-1cc47cbd-44bf-45e0-ba41-bf12baf482d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2MDg3MjcsIm5iZiI6MTcwMTYwODQyNywicGF0aCI6Ii80MTM2ODgxLzI4NzM0MDU3MC0xY2M0N2NiZC00NGJmLTQ1ZTAtYmE0MS1iZjEyYmFmNDgyZDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDNUMTMwMDI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjdkNGEwYzZhOGYxZTFiMDQ4MjBiZWZiYjgyOGRmNDc5NTgzZmYyOTA4YzdmZWRlY2RkOGY3NTcyYTE0ZTgwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8kmj5uIaRHXT6AUU0eCSrnQcrVz7u3V7wD51aQVMDO0)

Grazie mille, provvedo! 😉

**Comment by HandyMenny** [comment]
Giusto per informazione, il problema del calcolo del PUN F23 è che non è calcolato dal GME, quindi i vari venditori hanno un po' di flessibilità. Quello che voglio dire è che il metodo usato da A2A e CH4 è solo uno dei modi per calcolare il PUN F23. Non è l'unico.

Ad esempio alcuni, tra cui anche Arera, utilizzano una media ponderata sulle ore:
https://www.arera.it/consumatori/offerte-standard-per-i-clienti-finali-placet
https://www.dolomitienergia.it/approfondimenti/guide/indici-gas-energia/indice-pun.html
https://lupatotinagaseluce.it/indice-pun/
https://www.enercom.it/indici-di-mercato/

**Comment by virtualdj** [comment]
@HandyMenny Interessante... Però danno i risultati, ma non il metodo per calcolarlo.
Possibile che ognuno possa fare come vuole?

**Comment by HandyMenny** [comment]
> Possibile che ognuno possa fare come vuole?

Certo è possibile. Per dire ci sono anche operatori che il PUN lo calcolano come media pesata sui tuoi consumi o chi si crea le sue fasce. 
E siamo anche fortunati che per l'energia elettrica i dati sono pubblicamente disponibili, per il gas ad es. non è così.

Comunque in teoria per i venditori ci sarebbe l'obbligo di fornire una tabella con i valori dell'indice utilizzato, che dovrebbe sopperire alla mancanza del metodo di calcolo. Ma a parte che non tutti lo rispettano, capita anche che pubblichino l'indice sbagliato...
