### ISSUE TITLE
Aggiunta funzioni

### ISSUE THREAD

**Issue by aleZZ2001** [virtualdj/pun_sensor#25]
Ciao, ho scoperto oggi questa integrazione ed è molto più comoda rispetto all'usare il multiscrape, volevo chiederti se potresti aggiungere anche (non so se è fattibile o quanto tempo ci voglia) tutti i costi dell'energia tipo art. 44, 44bis, 73.3  ecc. più costo dispacciamento, perdite di rete, spese di trasporto, imposte ecc. (in pratica ogni costo). i dati sono tutti reperibili in formato xml o csv dal portaleofferte (dove ci sono anche i costi del gas)

https://www.ilportaleofferte.it/portaleOfferte/it/open-data.page

ed infine diciamo per rendere il tutto perfetto aggiungere un campio variabile dove inserire il prezzo di commercializazione a discrezione dell'utente in base all'offerta che ha

**Comment by virtualdj** [comment]
> i dati sono tutti reperibili in formato xml o csv dal portaleofferte

Ciao, ho provato a scaricare le offerte in XML ma quella sembra una "raccolta" delle varie offerte dei fornitori... non un qualcosa di variabile giornalmente come questa integrazione.

> potresti aggiungere anche tutti i costi dell'energia tipo art. 44, 44bis, 73.3 ecc. più costo dispacciamento, perdite di rete, spese di trasporto, imposte ecc. (in pratica ogni costo)

Non sono molto preparato su questo, di sicuro non mi sembra semplice!
