### ISSUE TITLE
Prezzi PUN più bassi della realtà

### ISSUE THREAD

**Issue by Claudio1L** [virtualdj/pun_sensor#26]
Buongiorno

sarebbe interessante capire come vengono raccolti i prezzi del pun. Sembrano esserci delle differenze consistenti con i prezzi reali.

Anche facendo una media per le varie fasce, i prezzi dell'integrazione sembrano sostanzialmente più bassi.

Ad esempio oggi:

![immagine](https://github.com/virtualdj/pun_sensor/assets/97904190/b9d061f4-2e1e-40e4-9c9d-469dc099d9b8)

Mentre dalla tabella del MGP vedo:

![immagine](https://github.com/virtualdj/pun_sensor/assets/97904190/5c3797d1-655c-429f-a04b-eb9f0ce916fb)

https://www.mercatoelettrico.org/It/Esiti/MGP/TabellaEsitiMGPPrezzi.aspx

**Comment by virtualdj** [comment]
La risposta è nel README (visibile nella homepage del progetto). Quelli che mostri sono i prezzi MGP (Mercato del Giorno Prima) ovvero i prezzi giornalieri.

Quelli che mostra l'integrazione sono invece la media di questi MGP per ogni giorno da inizio mese, divisi per fascia. Perché è questo, alla fine, quello che pagherai: se guardi nelle tabelle dei fornitori ad ogni fine mese [esce il prezzo per fascia](https://www.a2a.it/assistenza/tutela-cliente/indici/indice-pun), che poi moltiplicato per i kWh e con l'aggiunta di tasse e costi fissi e spread del fornitore è il prezzo in bolletta.

I prezzi mostrati dall'integrazione saranno vicini a quelli pubblicati verso la fine di ogni mese, perché le medie si accumulano ed esistono tanti dati nel "paniere" con la media via via più precisa.

**Comment by Claudio1L** [comment]
ok, scusami ma non l'avevo capito.
In tal caso devo capire come fare, perchè nei miei template raccolgo i prezzi ogni giorno/mese/anno in base al pun di quel giorno. Mi piaceva di averlo per fasce, ma in questo caso quello che ottengo non è il pun del giorno x ma è il pun della media fino al giorno x per una data fascia. Ok, grazie, cerco di capire come cambiare le logiche di conteggio
