### ISSUE TITLE
Prezzo al dettaglio

### ISSUE THREAD

**Issue by leovj** [virtualdj/pun_sensor#27]
Buongiorno e innanzi tutto complimenti ha fatto un lavoro straordinario!
Ho subito installato e messo in funzione la tua integrazione anche perchè adesso (fino a Marzo 2024) ho il prezzo fisso ma aimè da quella data dovrò passare al variabile... Volevo capire una cosa: nel template sensor che hai generato e cioè
{{ (1.1 * (states('sensor.pun_prezzo_fascia_corrente')|float(0) + 0.0087 + 0.04 + 0.0227))|round(3) }}
I Tre valori che sommi (0.0087, 0.04, 0,0227) sono le tasse e i costi fissi, dovrei andare a cercare questi valori sulla mia bolletta ma vorrei capire a quali voci corrispondono..

Thanks

**Comment by virtualdj** [comment]
Dai un'occhiata [qui](https://github.com/virtualdj/pun_sensor/issues/20#issuecomment-1775672871), dove avevo più o meno risposto alla stessa domanda.
