### ISSUE TITLE
Prezzo diverso rispetto al GME

### ISSUE THREAD

**Issue by iz8mbw** [virtualdj/pun_sensor#28]
Ciao,
complimenti e grazie per questa integrazione!
Volevo chiedere coma mai il prezzo PUN dell'integrazione è sempre più basso di quello del sito GME.
Per esempio per oggi l'integrazione fornisce 0,118692 €/kWh come prezzo mono-orario, invece il sito GME fornisce 0,13515 €/kWh:
![image](https://github.com/virtualdj/pun_sensor/assets/3474082/1b50eef6-a56f-4fc9-a5ef-eb5fa7e1d6a9)

![image](https://github.com/virtualdj/pun_sensor/assets/3474082/d83cc419-32c9-41bf-a769-c43815b4cefd)

![image](https://github.com/virtualdj/pun_sensor/assets/3474082/5bfa0810-b9bf-4752-8e1c-f2cd590729fc)

Grazie!

**Comment by virtualj** [comment]
L'integrazione fornisce la media mensile, tu stai guardando il prezzo giornaliero

**Comment by iz8mbw** [comment]
Ok.
Non sarebbe possibile aggiungere, nell'integrazione, anche un'altra entità che mostra il prezzo giornaliero?

**Comment by virtualdj** [comment]
> Non sarebbe possibile aggiungere, nell'integrazione, anche un'altra entità che mostra il prezzo giornaliero?

Non è lo scopo dell'integrazione, visto che comunque al prezzo in bolletta concorre la media del mese, non il prezzo giornaliero che si può estrarre con semplice sensore REST.
