### ISSUE TITLE
Integrazione ulteriori dati

### ISSUE THREAD

**Issue by Truehub23** [virtualdj/pun_sensor#29]
Ciao virtualdj, lavoro stupendo e ti faccio i complimenti.

Sarebbe interessante integrare altri valori al tuo progetto, provo ad aiutarti:

- **Corrispettivo perdite di rete**: fissato al **10%** attualmente (viene revisionato ogni 3 anni) pertanto puoi metterlo come costante, e comunque oscilla di poco.

- **Corrispettivo dispacciamento (PD)**: si trovano a questo indirizzo, dentro un excel: 

https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fwww.arera.it%2Fallegati%2Fdati_documenti%2Fprezzi%2Felettricita-domestici.xls&wdOrigin=BROWSELINK

- **Oneri di sistema (ASOS e ARIM)**: si trovano a questo indirizzo, dentro un excel:

https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fwww.arera.it%2Fallegati%2Fdati_documenti%2Fprezzi%2Felettricita-domestici.xls&wdOrigin=BROWSELINK

- **Accise e IVA**: si trovano qui: https://www.servizioelettriconazionale.it/it-IT/tariffe/costo-fornitura/tabella-imposte-energia-elettrica

Poi volevo indicarti che la media mensile PUN per fasce è presente sul sito Arera, facile da prendere e consultare:

https://www.arera.it/it/consumatori/placet.htm#econom

Penso sia fattibile, in questo modo se fai un calcolo hai un prezzo al kW molto vicino a quello finale.

Grazie ancora per il progetto!

**Comment by Truehub23** [comment]
EDIT: hanno cambiato OGGI POMERIGGIO il sito arera...gli excel ci sono ma in un altra posizione...

**Comment by virtualdj** [comment]
Neanche il link alla media mensile PUN funziona... cosa c'era scritto lì?
Perché se è il prezzo del mese precedente, questa integrazione non fa scraping ma calcola il prezzo del mese corrente in tempo reale.

**Comment by virtualdj** [comment]
OK, ma se i dati si trovano in quell'Excel e non cambiano spesso e li devi comunque inserire a mano in HA, quale sarebbe il vantaggio rispetto al template sensor che integra i costi fissi o per kWh?
