### ISSUE TITLE
I consumi vengono caricati su F2 anche se e' prevista la tariffa F3

### ISSUE THREAD

**Issue by robi59italy** [virtualdj/pun_sensor#33]
l'entity mi mostra che la tariffa in atto e' F3, ma i consumi odierni sono tutti caricati in F2....

**Comment by virtualdj** [comment]
Scusa, ma non mi è chiaro il problema. Ti riferisci al prezzo? Mi pare che punti correttamente al prezzo della fascia F3.

![Screenshot attuale](https://github.com/virtualdj/pun_sensor/assets/3251704/bff4f60d-8363-440c-92dd-dc08dcf15a5c)

L'integrazione non misura i *consumi odierni* ma rileva solamente i prezzi...

**Comment by robi59italy** [comment]
Anche se in questo momento sono in F3 i kWh consumati vengono aggiunti a sensor.meter_fasce_f2

**Comment by virtualdj** [comment]
OK, ma perché lo chiedi qui? Questa integrazione non fornisce l'entità `sensor.meter_fasce_f2`, sarà qualcosa che hai aggiunto tu...

**Comment by robi59italy** [comment]
Trovato...l'automazione passa il valore sempre a F2 i
