### ISSUE TITLE
Stato "non caricato" dopo aggiornamento

### ISSUE THREAD

**Issue by Pelmo23** [virtualdj/pun_sensor#44]
Buongiorno,
dopo l'aggiornamento della settimana scorsa l'integrazione non aggiorna più i valori delle fasce  (allego screenshot).
nessuna operazione mi risulta disponibile se non disabilitare l'integrazione.

Core: 2024.1.2
Supervisor: 2024.05.1
Operating System: 11.3
Frontend: 20240104.0

qualche suggerimento? grazie!

![pun_issue](https://github.com/virtualdj/pun_sensor/assets/139858966/21d68872-f6d0-45ae-8d3d-1075f3da1a75)

**Comment by moddroid94** [comment]
Ciao @Pelmo23 , potresti gentilmente caricare un log dell'integrazione?

Dovresti poterlo abilitare usando l'ultimo pulsante nello screen sotto:
![image](https://github.com/virtualdj/pun_sensor/assets/16489982/b4f07ca2-67c4-4f7b-8017-91deb9be5dc7)

Dopo aver riavviato Hassio ripremendo il pulsante dovrebbe scaricarti un file che puoi caricare direttamente qui. :)

**Comment by Pelmo23** [comment]
> Ciao @Pelmo23 , potresti gentilmente caricare un log dell'integrazione?
> 
> Dovresti poterlo abilitare usando l'ultimo pulsante nello screen sotto: ![image](https://private-user-images.githubusercontent.com/16489982/331150118-b4f07ca2-67c4-4f7b-8017-91deb9be5dc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4Njc1NDYsIm5iZiI6MTcxNTg2NzI0NiwicGF0aCI6Ii8xNjQ4OTk4Mi8zMzExNTAxMTgtYjRmMDdjYTItNjdjNC00ZjdiLTgwMTctOTFkZWI5YmU1ZGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDEzNDcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MTU4OTk4YjlmZjc3ZTI2YjcyNDBiMWVhZDZlYzViMGNhMmZlNzA4MzE5YWE0N2U4NWU2YTJjNWQ4MjRmMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tf6SxY6z8j6FoPdbSkIDu0tJiyVsU3Q8PR9lDjfHiJ4)
> 
> Dopo aver riavviato Hassio ripremendo il pulsante dovrebbe scaricarti un file che puoi caricare direttamente qui. :)

Ciao,
non ho la possibilità di attivare il debug, mi compare solo il link alla documentazione e a problemi noti.
devo forse abilitare qualche modalità avanzata?
grazie!

**Comment by moddroid94** [comment]
strano, non dovrebbe essere necessario alcuno step aggiuntivo, potrebbe non riuscire a caricare proprio l'integrazione.
Potresti provare a controllare nei log di sistema di hassio?  magari li' ce' qualcosa, controlla un attimo gli errori prima di caricarlo in quanto potrebbe contenere qualche informazione sensible. :)

**Comment by Pelmo23** [comment]
> strano, non dovrebbe essere necessario alcuno step aggiuntivo, potrebbe non riuscire a caricare proprio l'integrazione. Potresti provare a controllare nei log di sistema di hassio? magari li' ce' qualcosa, controlla un attimo gli errori prima di caricarlo in quanto potrebbe contenere qualche informazione sensible. :)

Logger: homeassistant.config_entries
Source: config_entries.py:2087
First occurred: 14 maggio 2024 alle ore 19:18:24 (4 occurrences)
Last logged: 08:33:45

Error occurred loading flow for integration pun_sensor: cannot import name 'SetupPhases' from 'homeassistant.setup' (/usr/src/homeassistant/homeassistant/setup.py)


File "/config/custom_components/pun_sensor/__init__.py", line 20, in <module>
from homeassistant.setup import SetupPhases, async_pause_setup
ImportError: cannot import name 'SetupPhases' from 'homeassistant.setup' (/usr/src/homeassistant/homeassistant/setup.py)

**Comment by virtualdj** [comment]
Purtroppo l'errore è causato dalla versione troppo vecchia di HA, che fa fallire l'istruzone:
```python
from homeassistant.setup import SetupPhases, async_pause_setup
```
Se non leggo male i commit, serve come minimo Home Assistant 2024.4.1.

Il problema è che se non metto quell'istruzione ricadiamo nel problema #39 e chi ha HA aggiornato riceve i warning.
Evviva le breaking changes!!!

Insomma, se non vuoi aggiornare HA, fai il downgrade di questa integrazione finché non trovo un sistema di far funzionare entrambe (certo che però... 😞).

**Comment by virtualdj** [comment]
Comunque appena posso sistemerò anche questo (o con un controllo versione, o con un controllo che l'oggetto esista).

**Comment by Pelmo23** [comment]
> Comunque appena posso sistemerò anche questo (o con un controllo versione, o con un controllo che l'oggetto esista).

ottimo grazie; come faccio intanto a fare il downgrade?

**Comment by virtualdj** [comment]
Non c'è una maniera semplice, bisogna andare su Github, scaricare la versione ZIP precedente alla commit incriminata e sostituire i file nella cartella custom_components della tua installazione.

Se hai ancora qualche giorno di pazienza vedo/vediamo se riusciamo a risolvere direttamente.

**Comment by virtualdj** [comment]
@Pelmo23 Adesso dovresti vedere le versioni/release quando scarichi da HACS (esempio [qui](https://github.com/virtualdj/pun_sensor/pull/45#issuecomment-2123384921)); quella che interessa a te è la **v0.6.0**. La versione la puoi leggere dentro il file `manifest.json` (non ho mai capito perché HA non mostra le versioni dei componenti 🤔).

@moddroid94 Io però nella mia istanza di prova **non riesco ad eseguire il downgrade**. Non so se succede anche a te... Quindi se ad esempio scelgo la v0.7.0 come dovrebbe fare @Pelmo23 in realtà mi scarica comunque la v0.8.0 (cioè l'ultima) e questo anche se cancello tutto e riparto con HACS da zero.

Eppure i tag sono giusti e anche gli ZIP che ho caricato manualmente nelle release. È un problema solo mio?

**Comment by moddroid94** [comment]
> @Pelmo23 Adesso dovresti vedere le versioni/release quando scarichi da HACS (esempio [qui](https://github.com/virtualdj/pun_sensor/pull/45#issuecomment-2123384921)); quella che interessa a te è la **v0.6.0**. La versione la puoi leggere dentro il file `manifest.json` (non ho mai capito perché HA non mostra le versioni dei componenti 🤔).

in teoria dalla schermata di HACS puoi vedere la versione scaricata, e' la pill in alto a sinistra:
![image](https://github.com/virtualdj/pun_sensor/assets/16489982/f048203c-d8f7-4362-a694-5d6f1fe88981)

> @moddroid94 Io però nella mia istanza di prova **non riesco ad eseguire il downgrade**. Non so se succede anche a te... Quindi se ad esempio scelgo la v0.7.0 come dovrebbe fare @Pelmo23 in realtà mi scarica comunque la v0.8.0 (cioè l'ultima) e questo anche se cancello tutto e riparto con HACS da zero.
> 
> Eppure i tag sono giusti e anche gli ZIP che ho caricato manualmente nelle release. È un problema solo mio?

Questo non l'ho testato sinceramente, provo a controllare.

**Comment by virtualdj** [comment]
> Edit: Ho testato e con me funziona, ho fatto redownload, selezionato la 0.7.0, fatto il reboot e sembra aver caricato la giusta versione.

@moddroid94 Con la fix #48 ho risolto per quanto riguarda le nuove versioni, ma se io in HACS seleziono la 0.6.0 non me la scarica: mi scarica sempre l'ultima (beta perché ho selezionato così), ma stavolta con il manifest corretto.

@Pelmo23 Puoi provare a vedere se a te funziona, selezioni la 0.6.0 dall'elenco e poi verifichi dal file `manifest.json` che ti abbia realmente scaricato quella versione. A me non va, ma a @moddroid94 sì.

**Comment by moddroid94** [comment]
> @moddroid94 Con la fix https://github.com/virtualdj/pun_sensor/pull/48 ho risolto per quanto riguarda le nuove versioni, ma se io in HACS seleziono la 0.6.0 non me la scarica: mi scarica sempre l'ultima (beta perché ho selezionato così), ma stavolta con il manifest corretto.

non riesco a capire come mai ma sospetto che sia un problema di HA o HACS, perche' la configurazione e' corretta, a meno che non ci metta un po' a pescare l'update nel file `hacs.json`, ma mi sembra strano e fondamentalmente dovrebbe comunque avere quel behavior di default
io comunque sono sull'ultima versione di tutto, supervisor, core e HACS

**Comment by virtualdj** [comment]
@moddroid94 Forse era un problema di caching. Ho rimosso tutto, riavviato, riscaricato l'integrazione e così finalmente è venuta già la 0.6.0. Evidentemente se non riavvii si "ricorda" i vecchi settaggi nonostante gli abbia detto di disinstallare (e la cartella l'aveva fatta sparire). 🤷🏻‍♂️

**Comment by Pelmo23** [comment]
> manifest.json

ciao, a me continua ad installare la 0.8.0.
ho prima rimosso, riavviato, installato indicando la 0.6.0, riavviato ma sul file manifest.json vedo sempre la 0.8.0

**Comment by virtualdj** [comment]
@Pelmo23 Con "rimosso" io intendo che devi cancellare l'integrazione dai dispositivi (quindi spariscono i sensori) e anche cancellare l'integrazione da HACS (mi pare si chiami Delete il comando) e a quel punto noti che la cartella `custom_components/pun_sensor` viene proprio eliminata.

A quel punto riavvii HA e dopo il riavvio provi a riscaricare da HACS. Ieri dopo 2 volte che ho fatto così a me ha funzionato.

**Comment by Pelmo23** [comment]
> @Pelmo23 Con "rimosso" io intendo che devi cancellare l'integrazione dai dispositivi (quindi spariscono i sensori) e anche cancellare l'integrazione da HACS (mi pare si chiami Delete il comando) e a quel punto noti che la cartella `custom_components/pun_sensor` viene proprio eliminata.
> 
> A quel punto riavvii HA e dopo il riavvio provi a riscaricare da HACS. Ieri dopo 2 volte che ho fatto così a me ha funzionato.

ho provato più volte a fare elimina ma non viene di fatto eliminato; riesco solo a disabilitarlo :(

**Comment by moddroid94** [comment]
ciao @Pelmo23 ,  nei log di HA vedi qualche errore strano?
La versione di HACS e' la 1.34 giusto?

comunque a volte HA non cancella correttamente le integrazioni ma le disabilita soltanto, se non e' quello che hai gia' fatto magari puo aiutarti, io di solito seguo questi step:

1. rimuovi integrazione da HA usando il pulsante nel menu' del device
![image](https://github.com/virtualdj/pun_sensor/assets/16489982/3d51f586-ac75-4380-9479-a221185067cb)

3. rimuovi integrazione da HACS usando il pulsante nel menu' dell'integrazione
4. riavvia HA, non quick reload, proprio reboot se puoi

![image](https://github.com/virtualdj/pun_sensor/assets/16489982/5a145195-78e7-4a41-a986-e19691a8ccc6)

5. reinstalla l'integrazione via HACS (v0.6.0)
6. riavvia HA, non quick reload ma basta anche solo il riavvio normale, non il reboot di sistema
7. aggiungi nuovamente l'integrazione dalla UI in HA

Ps. Le altre integrazioni riesci ad aggiornarle? perche' in qualche forum leggo anche che a volte qualche update di HA 'rompe' HACS e devi runnare nuovamente il comando di installazione per fixarlo, pero' appunto se e' quello non dovresti poter aggiornare nulla

**Comment by Pelmo23** [comment]
> ciao @Pelmo23 , nei log di HA vedi qualche errore strano? La versione di HACS e' la 1.34 giusto?
> 
> comunque a volte HA non cancella correttamente le integrazioni ma le disabilita soltanto, se non e' quello che hai gia' fatto magari puo aiutarti, io di solito seguo questi step:
> 
> 1. rimuovi integrazione da HA usando il pulsante nel menu' del device
>    ![image](https://private-user-images.githubusercontent.com/16489982/333203512-3d51f586-ac75-4380-9479-a221185067cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NzU1NzMsIm5iZiI6MTcxNjQ3NTI3MywicGF0aCI6Ii8xNjQ4OTk4Mi8zMzMyMDM1MTItM2Q1MWY1ODYtYWM3NS00MzgwLTk0NzktYTIyMTE4NTA2N2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE0NDExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxYmU3NmFhZWQ2NTA0NGFkN2I0MWYxYjc5ZDYyODdlNjM3N2M1MzE2Y2RhZTYyOGM3YTdjZGZjYmM3YjlkNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mhJkbNaySEK87rDjiJ96DfCIkCT2ZRRUtQX2hc47cSE)
> 2. rimuovi integrazione da HACS usando il pulsante nel menu' dell'integrazione
> 3. riavvia HA, non quick reload, proprio reboot se puoi
> 
> ![image](https://private-user-images.githubusercontent.com/16489982/333196566-5a145195-78e7-4a41-a986-e19691a8ccc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NzU1NzMsIm5iZiI6MTcxNjQ3NTI3MywicGF0aCI6Ii8xNjQ4OTk4Mi8zMzMxOTY1NjYtNWExNDUxOTUtNzhlNy00YTQxLWE5ODYtZTE5NjkxYThjY2M2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE0NDExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MzkwNjIwZmQzZTdmMTE4ZTgyM2U1NzkwYWVmNDk2MDgyMmUxYWFjMmMxNzY4ZWI0M2EwYmRhZGU3ZmVmNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QHGvy61KskPau7jwppQocelNY8DHCMIhG4IeYD0umXI)
> 
> 5. reinstalla l'integrazione via HACS (v0.6.0)
> 6. riavvia HA, non quick reload ma basta anche solo il riavvio normale, non il reboot di sistema
> 7. aggiungi nuovamente l'integrazione dalla UI in HA
> 
> Ps. Le altre integrazioni riesci ad aggiornarle? perche' in qualche forum leggo anche che a volte qualche update di HA 'rompe' HACS e devi runnare nuovamente il comando di installazione per fixarlo, pero' appunto se e' quello non dovresti poter aggiornare nulla

il mio problema è che facendo il punto 1 non succede nulla, rimane li e non da nessun errore...

**Comment by virtualdj** [comment]
Sistemato con la versione **v0.9.0** appena rilasciata.
