### ISSUE TITLE
Setup failed for custom integration pun_senso

### ISSUE THREAD

**Issue by bwillyb** [virtualdj/pun_sensor#51]
da giorni ricevo questo messaggio

Setup failed for custom integration pun_sensor: Unable to import component: cannot import name 'SetupPhases' from 'homeassistant.setup' (/usr/src/homeassistant/homeassistant/setup.py)

**Comment by virtualdj** [comment]
Con che versione dell'integrazione? Perché la 0.9.0 dovrebbe risolvere proprio quell'errore.

**Comment by bwillyb** [comment]
0.9.0 home assistant core

**Comment by bwillyb** [comment]
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: homeassistant.setup
Source: custom_components/pun_sensor/__init__.py:20
Integration: Prezzi PUN del mese (documentation, issues)
First occurred: 09:48:03 (1 occurrences)
Last logged: 09:48:03

Setup failed for custom integration pun_sensor: Unable to import component: cannot import name 'SetupPhases' from 'homeassistant.setup' (/usr/src/homeassistant/homeassistant/setup.py)
Traceback (most recent call last):
  ```
File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/pun_sensor/__init__.py", line 20, in <module>
    from homeassistant.setup import SetupPhases, async_pause_setup
ImportError: cannot import name 'SetupPhases' from 'homeassistant.setup' (/usr/src/homeassistant/homeassistant/setup.py)

```

**Comment by virtualdj** [comment]
Non credo sia **realmente** la 0.9.0 perché se noti nel codice non c'è quella riga alla posizione 20 come indicato nell'errore.

Verifica il file manifest.json dentro la cartella `custom_components/pun_sensor`: ho il sospetto che non ci sarà scritto 0.9.0 lì dentro.

Prova a rimuovere l'integrazione da HACS, riavviare HA, riscaricare da HACS e riavviare.

**Comment by moddroid94** [comment]
@virtualdj  Ho provato a scaricare il file zip e non sembra contenere le modifiche dell'ultima commit, probabilmente l'action ha avuto qualche errore con la creazione dello zip?

**Comment by virtualdj** [comment]
@moddroid94 Vedo... Però io l'avevo provata con HACS, boh, il caching fa brutti scherzi a questo punto.

**Comment by moddroid94** [comment]
> @moddroid94 Vedo... Però io l'avevo provata con HACS, boh, il caching fa brutti scherzi a questo punto.

Eh si probabilmente c'e qualche punto nella crezione delle release che probabilmente ci sfugge, non sono nemmeno sicuro che la release che ho draftato abbia i change, per quello dicevo di farla in pre almeno prima vediamo gli zip e se tutto va bene la mettiamo public

**Comment by bwillyb** [comment]
> Non credo sia **realmente** la 0.9.0 perché se noti nel codice non c'è quella riga alla posizione 20 come indicato nell'errore.
> 
> Verifica il file manifest.json dentro la cartella `custom_components/pun_sensor`: ho il sospetto che non ci sarà scritto 0.9.0 lì dentro.
> 
> Prova a rimuovere l'integrazione da HACS, riavviare HA, riscaricare da HACS e riavviare.

mi da versione 
 "version": "0.0.0"

**Comment by virtualdj** [comment]
@moddroid94 Fatto pre-release, controllati gli ZIP, impostata come latest e public.

@bwillyb Prova con la v0.9.2 appena rilasciata. A me pare OK, ha sia la versione nel manifest che le righe corrette.
Fammi sapere!

**Comment by moddroid94** [comment]
Ho aggiornato e sembra essere tutto corretto sul mio👌

**Comment by bwillyb** [comment]
> @moddroid94 Fatto pre-release, controllati gli ZIP, impostata come latest e public.
> 
> @bwillyb Prova con la v0.9.2 appena rilasciata. A me pare OK, ha sia la versione nel manifest che le righe corrette. Fammi sapere!

ho reinstallato ora ricevo questo
`Logger: homeassistant.setup
Source: setup.py:379
First occurred: 08:02:20 (1 occurrences)
Last logged: 08:02:20

Unable to prepare setup for platform pun_sensor.sensor: Platform not found (cannot import name 'override' from 'typing' (/usr/local/lib/python3.11/typing.py)).`

**Comment by moddroid94** [comment]
Sembra essere un problema già riscontrato, sfortunatamente non sono riuscito a trovare soluzioni né possibili spiegazioni, potrebbe essere un bug di Homeassistant.

L'issue:
 
https://github.com/home-assistant/core/issues/117167

Purtroppo non posso approfondire oggi, proverò nel weekend in caso anche @virtualdj non avesse soluzioni

**Comment by virtualdj** [comment]
Così su due piedi non trovo nulla neppure io, tra l'altro quell'issue è stata chiusa senza dare spiegazioni (anzi, l'ultimo commento scrive che il problema è ancora presente).

È strano che un decorator che tecnicamente penso addirittura non faccia nulla (@bwillyb potresti provare a rimuovere la parola `override` dal file sia nell'import che più sotto dove ha la chiocciola davanti) riesca a rompere HA in questo modo 🤨

**Comment by moddroid94** [comment]
> Così su due piedi non trovo nulla neppure io, tra l'altro quell'issue è stata chiusa senza dare spiegazioni (anzi, l'ultimo commento scrive che il problema è ancora presente).
>
>È strano che un decorator che tecnicamente penso addirittura non faccia nulla (@bwillyb potresti provare a rimuovere la parola >override dal file sia nell'import che più sotto dove ha la chiocciola davanti) riesca a rompere HA in questo modo 🤨
>

Rileggendo il codice vedo che comunque non c'e' override nella def "extra_state_attribute" per il sensore precedente, quindi credo possa essere rimosso senza problemi, anche perche' tecnicamente l'override e' ridondante in questo caso, cioe' tutte le def sono override degli stati base di HA, quindi non avrebbe dovuto funzionare proprio se fosse stato necessario.

No potendo testare il problema non ho garanzia, ma sembra abbastanza sicuro rimuoverlo.

**Comment by virtualdj** [comment]
> Rileggendo il codice vedo che comunque non c'e' override nella def "extra_state_attribute" per il sensore precedente, quindi credo possa essere rimosso senza problemi

Lo penso anch'io, anche da altre parti (inteso come altre integrazioni) non lo vedo, quindi adesso faccio una hotfix per rimuoverlo.

**Comment by moddroid94** [comment]
> > Rileggendo il codice vedo che comunque non c'e' override nella def "extra_state_attribute" per il sensore precedente, quindi credo possa essere rimosso senza problemi
> 
> Lo penso anch'io, anche da altre parti (inteso come altre integrazioni) non lo vedo, quindi adesso faccio una hotfix per rimuoverlo.
> 
> EDIT P.S.: Ma abbiamo così tanti download? Più di 700?!? 😯

Si infatti ci sono rimasto 🤣
Beh e' indubbiamente utile, e non mi sembra che ci siano altre opzioni, a momenti manco i fornitori ti danno questa info 🤣

Comunque per l'hotfix va bene, se preferisci fare come con l'ultima che facciamo prima pre e poi release cosi' controlliamo gli zip, anche se in teoria non dovrebbe dare problemi se passiamo a 0.9.3 🤞

**Comment by virtualdj** [comment]
@bwillyb Prova con la 0.9.3... forse è la volta buona 🤞 😄

**Comment by bwillyb** [comment]
> @bwillyb Prova con la 0.9.3... forse è la volta buona 🤞 😄

ok funziona
