### ISSUE TITLE
PUN Display

### ISSUE THREAD

**Issue by Bonnyfede00** [virtualdj/pun_sensor#53]
Ciao a tutti, sto pensando di costruire un dispositivo utilizzando un Raspberry zero 2 W e un display e-ink per mostrare in tempo "reale" il prezzo del PUN. Come potrei adattare questa soluzione per il mio scopo? (Chiaramente senza passare per home assistant)
Grazie :)

**Comment by virtualdj** [comment]
Beh io il prezzo lo visualizzo su un LaMetric Time utilizzando Home Assistant come backend. Non ho pratica di Raspberry, però se ci gira Python puoi adattare il codice, scaricarti i prezzi e mostrarti i valori.
O magari potresti usare ESPHome collegato ad un display... ESPHome "parla" nativamente con Home Assistant (che però devi far girare da qualche altra parte).

**Comment by Bonnyfede00** [comment]
Python ci gira, allora mi studierò meglio come integrare il codice ed estrarre lo stretto necessario escludendo home assistant. Grazie comunque.
