### ISSUE TITLE
Importi fasce errati?

### ISSUE THREAD

**Issue by Stinocon** [virtualdj/pun_sensor#54]
Salve a tutti!
Innanzitutto grazie per il componente. Da qualche tempo però non mi tornano gli importi delle fasce. 
Da quel poco che conosco l'argomento il prezzo dell'energia dovrebbe essere decrescente in funzione della fascia, dove:

- F1 più cara
- F2 intermedia
- F3 meno cara

Se però verifico i valori del componente salta fuori che:

- F1 intermedia
- F2 più cara
- F3 meno cara

Quindi è come se il prezzo di F1 ed F2 fosse invertito. 
Qualcun'altro ha notato questo? Oppure sono io che sto male interpretando i dati?

<img width="402" alt="immagine" src="https://github.com/user-attachments/assets/5ca693a7-8dbc-42e9-af93-802216a28a65">

Grazie!

**Comment by virtualdj** [comment]
Non è detto! Il prezzo viene stabilito dal mercato e potrebbe essere che la fascia F2 sia più costosa delle altre, infatti questa cosa si è già verificata [anche nei mesi scorsi](https://www.a2a.it/assistenza/tutela-cliente/indici/indice-pun) (sebbene con entità maggiore).

![Dati PUN da A2a](https://github.com/user-attachments/assets/49a11f0c-ccbb-4721-8905-8870ebfef04a)

**Comment by Stinocon** [comment]
Porca miseria! Avevo dato come verità assoluta il fatto che le fasce dovessero essere sempre "una più costosa dell'altra a salire" e invece non è così - questo componente diventa ancora più utile.

Grazie!
