### ISSUE TITLE
Supporto statistiche di stato

### ISSUE THREAD

**Issue by daveB30** [virtualdj/pun_sensor#57]
Ho notato che per tutti i sensori PUN non sono disponibili le statistiche di stato, somma e cambiamento.
Sono invece selezionabili media, min e max.

![Senza nome](https://github.com/user-attachments/assets/a82fdb38-dc7e-4133-bada-6c273f7bef38)

Nello storico trovo tutti i dati (comprese le LTS) e lo state_class: measurement è correttamente definito.

<img width="1618" alt="image" src="https://github.com/user-attachments/assets/6c922a63-0f40-48b9-86e6-25c7db7692e0">

<img width="908" alt="image" src="https://github.com/user-attachments/assets/b301a17e-703b-44e4-99c8-af4636b1c2e2">

E' fattibile attivare il supporto o bisogna creare un sensore statistico?

**Comment by daveB30** [comment]
Ho studiato un pochino la documentazione di HA e ritengo tu abbia ragione, sia riguardo le statistiche attive in ragione della classe di stato sia la scelta della classe del sensore.
Qui la spiegazione: [https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes](url)

Tuttavia, poter trattare il sensore PUN come state_class: total permetterebbe tramite le statistiche di ottenere lo stato (quindi il valore dei PUN) alla fine di ciascun mese. Certo, si tratta di una "misura" di un valore, ma è una misura che concettualmente si resetta ogni mese e che a fine mese mostra un valore "totale" come fosse un utility meter...

**Comment by virtualdj** [comment]
> Tuttavia, poter trattare il sensore PUN come state_class: total permetterebbe tramite le statistiche di ottenere lo stato (quindi il valore dei PUN) alla fine di ciascun mese

Eh no... `state_class: total` si usa nei sensori che presentano un valore che si incrementa continuamente come ad esempio un contatore che misura i kWh consumati. Non si può usare questo per il PUN, che è una misura.

> Certo, si tratta di una "misura" di un valore

Esattamente, è una misura di un calcolo giornaliero. Se si usasse il `state_class: total` di prima il valore non potrebbe mai diminuire, cosa che invece è possibile. 

> ma è una misura che concettualmente si resetta ogni mese e che a fine mese mostra un valore "totale" come fosse un utility meter

Se così fosse non potresti usarlo giornalmente, ma solo a fine mese. Quindi non va bene.
