### ISSUE TITLE
Cambio sorgente sito GME

### ISSUE THREAD

**Issue by g1za** [virtualdj/pun_sensor#59]
Ciao, col 1 ottobre il sito a cui fare riferimento (prima della sua dismissione del 31 dicembre, in favore del nuovo) diventa `https://storico.mercatoelettrico.org`.
Andrebbe aggiornato all'interno del componente perché al momento questo non riesce più a scaricare i dati e infatti ho tutte le entità `unavailable`.
Ciao!

[https://www.mercatoelettrico.org/it-it/Home/MediaGME/ArchivioNews?id=6350](url)

**Comment by g1za** [comment]
Risolto con #60

**Comment by g1za** [comment]
Lascio aperto fino al merge della PR per evitare duplicati

**Comment by virtualdj** [comment]
Grazie mille per la PR (che ha generato la v0.9.4). Ovviamente avrei dovuto prendermi per tempo, ma sono messo malissimo ultimamente... 😑

Dato che funziona, intanto andiamo avanti così, poi vedrò di darmi da fare a rilasciare la versione che usa il nuovo sito.

**Comment by Tagliax** [comment]
@virtualdj @g1za  Grazie ragazzi! 🥇
