### ISSUE TITLE
ottimo!

### ISSUE THREAD

**Issue by doppiaemme** [virtualdj/pun_sensor#6]
Ciao, ho trovato per caso questo progetto!
Io utilizzavo anche un altro componente per ricavare il PUN aggiornato, ma quello è basato sul Multiscraper della pagina dove pubblicano il valore aggiornato.
Da quel che vedo tu invece scarichi l'XML e poi in base all'orario estrai un prezzo e lo categorizzi per F1, F2 ed F3, corretto?
Molto interessante devo dire.
Se posso darti qualche suggerimento per delle "feature request":

1. sarebbe ottimo se si potesse memorizzare uno storico dei mesi passati, ovvero i prezzi a consuntivo per ogni mese dell'anno, in modo da vedere l'andamento dei prezzi
2. inserire un "previsore" di costi reali a partire dal PUN. Un metodo molto grezzo e facile è di aggiungere un markup fisso al prezzo del PUN. Ovviamente dipende dai costi fissi (tipo io ho 8KW di potenza impegnata) ma nel mio caso il markup che ho notato è in media un +58% rispetto al PUN (es. se a febbraio il pun era in media 0,17 €/kwh il costo reale in bolletta finito era 0,29 €/kwh.
Per un calcolo invece molto più preciso andrebbe seguito il metodo di calcolo del fornitore che usa un spread suo più costi variabili. Ho un foglio excel trovato da qualche parte ma non ho mai avuto nè il tempo nè le competenze per metterlo insieme.

**Comment by virtualdj** [comment]
> quello è basato sul Multiscraper della pagina dove pubblicano il valore aggiornato.

Anch'io prima di sviluppare questo utilizzavo Multiscraper per leggere il PUN giornaliero. Tuttavia, dato che poi la bolletta si paga sul medio mensile, ho deciso di cambiare.

> Da quel che vedo tu invece scarichi l'XML e poi in base all'orario estrai un prezzo e lo categorizzi per F1, F2 ed F3, corretto?

Sì, tento di "inseguire" la media giorno per giorno cosicché a fine mese si avrà il valore che apparirà nelle tabelle ufficiali, [tipo questa](https://www.a2aenergia.eu/assistenza/tutela-cliente/indici/indice-pun). Se non ci sono grosse variazioni, già a metà mese ti puoi fare un'idea di quello che pagherai al kWh.

> Molto interessante devo dire.

Grazie! È la mia prima esperienza in Python e sono veramente andato via di testa per capire come cavolo scrivere una integrazione con Home Assistant, come si può intuire (sarcasmo) dal README.

Mi piacerebbe capire **come calcolare correttamente la F23**, ma non riesco a trovare da nessuna parte la spiegazione e, nei posti dove c'è scritto qualcosa, poi se si prova a fare il calcolo con i dati giornalieri questi non coincidono mai con quelli delle tabelle mensili del PUN. Cosa che, al contrario, succede con la mono-oraria e con le altre 3 fasce (F1, F2, F3). Quindi qualcuno non la racconta giusta!

> 1. sarebbe ottimo se si potesse memorizzare uno storico dei mesi passati

Non l'ho messo apposta, perché in Home Assistant non c'è un vero modo di memorizzare le cose. Però se ti interessa puoi tenere fisso il valore copiandolo su un sensore di input o anche una [variabile](https://github.com/snarky-snark/home-assistant-variables) con una semplice automazione da eseguire l'ultimo giorno del mese.

> ovvero i prezzi a consuntivo per ogni mese dell'anno, in modo da vedere l'andamento dei prezzi

Se ti interessa solo l'andamento (non in Home Assistant) puoi vedere [pun-fasce](https://github.com/virtualdj/pun-fasce).

> 2. inserire un "previsore" di costi reali a partire dal PUN.

Anche qui non ho voluto farlo per non complicare eccessivamente l'integrazione, dato che ogni fornitore usa metodi di calcolo diversi. Questo comunque è risolvibile con un template sensor basato su questa integrazione, dove puoi fare tutti i calcoli che vuoi... ad esempio io ho fatto così:

```
      - unique_id: prezzo_attuale_energia
        name: 'Prezzo attuale energia'
        icon: mdi:currency-eur
        unit_of_measurement: '€/kWh'
        state: >
          {{ (1.1 * (states('sensor.pun_prezzo_fascia_corrente')|float(0) + 0.0087 + 0.04 + 0.0227))|round(3) }}
```
