### ISSUE TITLE
Il recupero dei prezzi ha smesso di funzionare dopo upgrade di home assistant

### ISSUE THREAD

**Issue by liquidand** [virtualdj/pun_sensor#61]
Dopo aver aggiornato home assistant alla release:
Core
2024.9.3
Frontend
20240909.1
prezziPun ha smesso di funzionare. Le entità sono tutte in questo stato:
![image](https://github.com/user-attachments/assets/56e246a1-794d-414a-b34e-56d8586d8d33)

**Comment by liquidand** [comment]
[home-assistant_pun_sensor_2024-10-03T09-59-19.263Z.log](https://github.com/user-attachments/files/17242482/home-assistant_pun_sensor_2024-10-03T09-59-19.263Z.log)
Allego debug log

**Comment by cobraviola** [comment]
Anche a me, ma probabilmente già da prima dell'aggiornamento

**Comment by Kedryn** [comment]
Ma come? a me Hacs continua a darmi la 0.9.3 e basta
