### ISSUE TITLE
Sensori "non disponibili"

### ISSUE THREAD

**Issue by Ector73** [virtualdj/pun_sensor#63]
Da un pò di giorni i sensori dell'integrazione non si aggiornano più. Sul portale www.mercatoelettrico.org c'è scritto che dal 1 ottobre il sito è raggiungibile ad un nuovo indirizzo. Forse è lì il problema.

Registratore: custom_components.pun_sensor
Fonte: custom_components/pun_sensor/__init__.py:335
Integrazione: Prezzi PUN del mese (documentazione, problemi)
Prima occorrenza: 09:15:57 (16 occorrenze)
Ultima registrazione: 10:08:50

Errore durante l'aggiornamento via web, nuovo tentativo tra 1 minuto.
Errore durante l'aggiornamento via web, nuovo tentativo tra 10 minuti.
Errore durante l'aggiornamento via web, nuovo tentativo tra 60 minuti.
Traceback (most recent call last):
  File "/config/custom_components/pun_sensor/__init__.py", line 216, in _async_update_data
    archive = zipfile.ZipFile(io.BytesIO(await response.read()))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1349, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1416, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/pun_sensor/__init__.py", line 335, in update_pun
    await self._async_update_data()
  File "/config/custom_components/pun_sensor/__init__.py", line 219, in _async_update_data
    raise UpdateFailed('Archivio ZIP scaricato dal sito non valido.')
homeassistant.helpers.update_coordinator.UpdateFailed: Archivio ZIP scaricato dal sito non valido.

**Comment by leovj** [comment]
Si sono non disponibili anche per me..

**Comment by Disincentivato** [comment]
Si non funzionano più.

**Comment by virtualdj** [comment]
Dovete aggiornare all'ultima versione 0.9.4.

**Comment by Ector73** [comment]
risolto...non avevo visto che era stato rilasciato un aggiornamento (non dovrebbe presentarmelo in automatico HA?).
Ho visto anche che c'erano state altre segnalazioni in merito... e di questo chiedo venia! :-)
Grazie di tutto!

**Comment by Disincentivato** [comment]
Ciao! Grazie per la segnalazione. Posso chiedere come si aggiorna dato che non viene segnalato in HA?

**Comment by virtualdj** [comment]
@Disincentivato 

Con lo stesso metodo con cui l'hai installato inizialmente.
Ovvero:
- se hai usato lo ZIP manualmente, scarichi il nuovo ZIP dalla sezione Releases e lo decomprimi sopra il vecchio
- se hai usato HACS, allora sarà lui che ti propone l'aggiornamento: clicca su HACS nel menu sul lato sinistro di HA e a destra vedrai la lista dei pacchetti (incluso questo) che prevedono un aggiornamento. Se non te lo mostrasse, clicca su **HACS > Integrazioni**, poi il tasto verde in alto per nascondere quelle suggerite, quindi nella lista che rimane su **Prezzi PUN del mese**. Lì puoi forzare un nuovo scaricamento con il pulsante overflow (tre lineette verticali).

**Comment by Disincentivato** [comment]
> @Disincentivato
> 
> Con lo stesso metodo con cui l'hai installato inizialmente. Ovvero:
> 
> * se hai usato lo ZIP manualmente, scarichi il nuovo ZIP dalla sezione Releases e lo decomprimi sopra il vecchio
> * se hai usato HACS, allora sarà lui che ti propone l'aggiornamento: clicca su HACS nel menu sul lato sinistro di HA e a destra vedrai la lista dei pacchetti (incluso questo) che prevedono un aggiornamento. Se non te lo mostrasse, clicca su **HACS > Integrazioni**, poi il tasto verde in alto per nascondere quelle suggerite, quindi nella lista che rimane su **Prezzi PUN del mese**. Lì puoi forzare un nuovo scaricamento con il pulsante overflow (tre lineette verticali).

In realtà l'avevo installato con HACS, mi sono accorto che la repository non era più presente e quindi non mi segnalava l'aggiornamento. Una volta reinserita ho aggiornato. Grazie ancora!
