### ISSUE TITLE
PUN orario

### ISSUE THREAD

**Issue by BogNik72** [virtualdj/pun_sensor#64]
Ciao, sarebbe possibile implementare questo dato?

**Comment by virtualdj** [comment]
Ciao, si potrà fare quando implementerò quanto scritto [QUI](https://github.com/virtualdj/pun_sensor/issues/42#issuecomment-2392313004), cioè una volta memorizzato il prezzo zonale orario per il giorno successivo, costa poco fare lo stesso anche per il PUN.

**Comment by BogNik72** [comment]
Grazie e comunque ottimo lavoro!

**Comment by virtualdj** [comment]
Lascio aperto finché non avrò fatto.
Ti chiedo però di avere pazienza perché in questo periodo ho altri progetti con priorità maggiore...

**Comment by virtualdj** [comment]
Il sensore è presente nella v2.0.0 (attualmente in pre-release).
