### ISSUE TITLE
non carica più i valori del PUN

### ISSUE THREAD

**Issue by schematt** [virtualdj/pun_sensor#65]
Dopo l'aggiornamento a 2024.10.1 non carica più i valori del PUN.
<img width="468" alt="Screenshot 2024-10-06 alle 15 09 57" src="https://github.com/user-attachments/assets/fbeb1504-6f84-4666-807d-eb4768819499">

**Comment by virtualdj** [comment]
@schematt
Ciao, sicuro che di avere aggiornato l'integrazione all'ultima versione (0.9.4)?

**Comment by schematt** [comment]
mi dice 0.5.0
<img width="345" alt="Screenshot 2024-10-06 alle 16 45 15" src="https://github.com/user-attachments/assets/8789a9e2-683c-4a84-a2fe-057ce6b5ff13">

**Comment by schematt** [comment]
ho provato ad aggiornare manualmente tutte le unità ma non è cambiato niente.

**Comment by schematt** [comment]
aggiornato con Hans a 0.9.4 e funziona tutto.
GRAZIE!!!
