### ISSUE TITLE
Fork per i prezzi zonali

### ISSUE THREAD

**Issue by Gariam-1** [virtualdj/pun_sensor#70]
Posto qui in assenza delle discussioni.

Ho creato una fork dove al posto del PUN vengono forniti i prezzi zonali (per la zona selezionata), inoltre ho aggiunto il prezzo orario dell'ora corrente e la possibilità di non calcolare la media mensile ma fornire solo i dati odierni.

Inizialmente fatto perchè volevo calcolare anche quanto quadagno con i pannelli solari, ma poi ho scoperto che dal 1 gennaio 2025 il PUN andrà in pensione a favore dei prezzi zonali anche per l'acquisto di energia, quindi doppio vantaggio.

Per il calcolo dei prezzi delle fasce ho utilizzato un nuovo approccio, tramite una media pesata sul fabbisogno orario previsto. Ma non sono del tutto sicuro che sia corretto, e non è ancora passato abbastanza tempo per confrontare i dati con quelli pubblici.

Link: https://github.com/Gariam-1/Prezzi-zonali-GME

**Comment by virtualdj** [comment]
> Ho creato una fork dove al posto del PUN vengono forniti i prezzi zonali (per la zona selezionata), inoltre ho aggiunto il prezzo orario dell'ora corrente

In realtà, con estrema lentezza visto il mio poco tempo a disposizione, ci stavo lavorando pure io viste le notevoli richieste. Controlla la branch `feat-prezzo-zonale`, mi manca ancora la parte relativa all'UI di selezione delle zone.

> poi ho scoperto che dal 1 gennaio 2025 il PUN andrà in pensione a favore dei prezzi zonali anche per l'acquisto di energia

Pare non sia proprio così, almeno [leggendo qui](https://www.dday.it/redazione/51357/dal-2025-i-cittadini-di-alcune-regioni-avrebbero-potuto-pagare-meno-lenergia-invece-pagheranno-sempre-uguale). Per l'acquisto ci sarà sempre questo **PUN Index GME** che non ho capito se sarà disponibile allo stesso endpoint dal quale lo leggiamo ora e sarà comunque una media pesata delle varie zone.

> Per il calcolo dei prezzi delle fasce ho utilizzato un nuovo approccio, tramite una media pesata sul fabbisogno orario previsto.

Come mai? Attualmente in bolletta si paga il valore medio dei prezzi per fascia di tutti i giorni del mese, quindi comunque credo dovrà essere il GME a pubblicare nel MGP i dati corretti che, mediati, costituiranno il prezzo in bolletta.

**Comment by virtualdj** [comment]
Non mi quadra del tutto... L'integrazione, per come la intendo io, calcola il valore finale delle fasce e del mono-orario previste per il mese corrente, quindi i prezzi che **a tendere del fine** mese saranno quelli che, moltiplicati per i consumi, daranno il costo totale da pagare.

Sono quelli che trovi anche [QUI](https://www.a2a.it/assistenza/tutela-cliente/indici/indice-pun), per A2A. Tieni d'occhio la prima e l'ultima colonna.

![PUN ottobre e novembre 2024](https://github.com/user-attachments/assets/dbdb05a7-7668-48ac-a403-67a7f3c7f5b2)

> per il mono-fascia è come segue: `(F1 * numero_ore_f1 + F2 * numero_ore_f2 + F3 * numero_ore_f3) / 24` 

Come può dunque essere corretto questo calcolo? Dovresti anche dividerlo per il numero di giorni del mese (30 nel caso di novembre e 31 per ottobre).

> Tu invece hai fatto solo la media aritmetica delle singole ore.

Sì, perché così il calcolo del prezzo mensile della fascia mono-oraria risulta corretto. Confrontando i due algoritmi, i risultati sono questi:

```text
# novembre, mono, tua versione
(mean(f1) * len(f1) + mean(f2) * len(f2) + mean(f3) * len(f3)) / 24 / 30
0.13074094630555558 => 0.130740

# novembre, mono, media di tutto (mia)
mean(monoorario)
0.13092278350486788 => 0.130920

# ottobre, mono, tua versione
(mean(f1) * len(f1) + mean(f2) * len(f2) + mean(f3) * len(f3)) / 24 / 31
0.11684507849462367 => 0.116850

# ottobre, mono, media di tutto (mia)
mean(monoorario)
0.11668823946308725 => 0.116690
```
Nessuno dei due metodi di calcolo corrisponde esattamente per il mese di novembre, mentre per quello di ottobre (e precedenti) il mio corrisponde esattamente una volta arrotondato al quinto decimale dopo la virgola.

> Infatti il dato non corrisponde con quello di GME.

Dove lo trovi? Perché io mi sono basato su quello di A2A che bene o male anche gli altri fornitori riportano sostanzialmente identico.

> E immagino che per la fascia F23 sia invece così: `(F2 * numero_ore_f2 + F3 * numero_ore_f3) / (numero_ore_f2 + numero_ore_f3)`

All'inizio volevo fare così, nei primi commit, ma appunto il risultato non corrispondeva **mai** con quello delle tabelle di A2A e degli altri fornitori (lì sopra). Poi [_virtualj_ qui in un commento](https://github.com/virtualdj/pun_sensor/issues/24#issuecomment-1829846806) ha trovato il metodo e, pur se incredulo, non posso che fargli i complimenti perché i risultati corrispondono!

```text
# novembre, F23, tua versione
(mean(f2) * len(f2) + mean(f3) * len(f3)) / (len(f2) + len(f3))
0.12445560575150301 => 0.124456

# novembre, F23, metodo virtualj
mean(f2) * .46 + mean(f3) * .54
0.12646199193243818 => 0.126462
round(mean(f2), 5) * .46 + round(mean(f3), 5) * .54
0.1264666 => 0.126467

# ottobre, F23, tua versione
(mean(f2) * len(f2) + mean(f3) * len(f3)) / (len(f2) + len(f3))
0.11304385776422764 => 0.113044

# ottobre, F23, metodo virtualj
mean(f2) * .46 + mean(f3) * .54
0.11509800217389474 => 0.115098
round(mean(f2), 5) * .46 + round(mean(f3), 5) * .54
0.11509559999999999 => 0.115096
```
Posso dire? Quando mi sono "imbarcato" in questa esperienza mai avrei pensato che fosse così tanto un casino.

**Comment by Gariam-1** [comment]
> Come può dunque essere corretto questo calcolo? Dovresti anche dividerlo per il numero di giorni del mese (30 nel caso di novembre e 31 per ottobre).

Le formule che ho scritto si riferiscono ad un giorno singolo. Poi certo che si farà la media dei giorni, se è quello l'obbiettivo.

> Nessuno dei due metodi di calcolo corrisponde esattamente per il mese di novembre, mentre per quello di ottobre (e precedenti) il mio corrisponde esattamente una volta arrotondato al quinto decimale dopo la virgola.

Eppure tutti quei calcoli fanno matematicamente la stessa cosa, perchè sia il mio che il tuo fanno la media aritmetica di tutte le ore, anche se il mio può non sembrare a prima vista. Perchè:
`(mean(f1) * len(f1) + mean(f2) * len(f2) + mean(f3) * len(f3)) / 24`
è uguale a:
`(sum(f1) / len(f1) * len(f1) + sum(f2) / len(f2) * len(f2) + sum(f3) / len(f3) * len(f3)) / 24`
di conseguenza:
`(sum(f1) + sum(f2) + sum(f3)) / 24`
 
> Dove lo trovi? Perché io mi sono basato su quello di A2A che bene o male anche gli altri fornitori riportano sostanzialmente identico.

Mi sono basato su valore giornaliero che da il sito di GME, che, appunto, poi mi sono accorto che ovviamente erano diversi, perchè la tua integrazione calcola il medio mensile. Una volta forzata a considerare solo oggi, i valori combaciavano. Ragione per cui poi ho cancellato quella frase.

> All'inizio volevo fare così, nei primi commit, ma appunto il risultato non corrispondeva **mai** con quello delle tabelle di A2A e degli altri fornitori (lì sopra). Poi [_virtualj_ qui in un commento](https://github.com/virtualdj/pun_sensor/issues/24#issuecomment-1829846806) ha trovato il metodo e, pur se incredulo, non posso che fargli i complimenti perché i risultati corrispondono!

Per quanto siano corretti i risultati, dubito che utilizzare dei numeri magici sbucati dal nulla come 0.46 e 0.54 sia una cosa ufficiale.
Per non parlare che, se è vero quello che c'è scritto negli ultimi messaggi di quel'issue, allora il valore sarebbe valido solo per alcuni. Se gia fanno sti casini con il PUN, con gli zonali sarà un incubo... tipo lo stesso fornitore che applica formule diverse per ogni zona...

**Comment by virtualdj** [comment]
> Per quanto siano corretti i risultati, dubito che utilizzare dei numeri magici sbucati dal nulla come 0.46 e 0.54 sia una cosa ufficiale.

Me ne rendo conto. Però vedila da un altro punto di vista: se formalmente la formula fosse corretta (quella della media di F2 e F3) però il risultato fosse sempre incoerente con quelli pubblicati (anche nelle bollette, eh!), cosa penseresti? Neppure se lo scrivessi nel README qualcuno mi darebbe ragione, perché semplicemente il risultato è diverso da quello reale.

Il metodo di calcolo dell'F23 io non l'ho trovato da nessuna parte, come scritto in quell'issue. Per questo all'inizio non avevo messo il sensore della fascia F23: non aveva senso darlo errato.

Poi però è saltata fuori quella formula e funziona... quindi ho cambiato idea e aggiunto il sensore. Ma continuo a non capire come se lo siano inventato.

> Se gia fanno sti casini con il PUN, con gli zonali sarà un incubo... tipo lo stesso fornitore che applica formule diverse per ogni zona...

Infatti sono già preoccupato.
