### ISSUE TITLE
Non sono scaricati i prezzi di F1, F2 e F3

### ISSUE THREAD

**Issue by maurizioandreotti60** [virtualdj/pun_sensor#8]
Ho installato l'integrazione ma viene viene visualizzato il prezzo della monorario e non quello delle tre fascie F1, F2 e F3.
Il prezzo della fascia corrente viene visualizzato.
Non ho attivato la casella _Usa solo dati reali ad inizio mese_

**Comment by virtualdj** [comment]
Puoi fare uno screenshot? Perché quello che affermi non dovrebbe essere possibile...
Ad esempio, il prezzo della fascia corrente è essenzialmente copiato da quello tra F1, F2 e F3 che è attivo all'orario corrente. Quindi è strano che il prezzo della fascia corrente venga visualizzato mentre quelle delle 3 fasce no.

Anche il log aiuterebbe...
